default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: 127.0.0.1
  username: docker
  password: docker

development:
  <<: *default
  database: stockwatcher_development

test:
  <<: *default
  database: stockwatcher_test

profile:
  <<: *default
  database: stockwatcher_development

production:
  <<: *default
  database: stockwatcher_development
